### PR TITLE
Fix type error

### PR DESCRIPTION
**Pull request by mdoi2**
Closes https://github.com/venables/koa-helmet/issues/95

### CODE REVIEW

**Comment by julienw** [comment]
ah interesting, this was working for me locally!
but the change looks good to me.
Sorry @venables for the error on my end.

**Comment by mdoi2** [comment]
@julienw 
Thank you for your confirmation!

> ah interesting, this was working for me locally!

Perhaps it is due to this setting in tsconfig.json?
`"skipLibCheck": true`

If this setting is set to false, an error will be displayed when opening `koa-helmet.d.ts` with an editor.

The reason it is true is probably because of [this error](https://github.com/rollup/rollup/issues/5199) in rollup.
I get this error when I run `tsc --noEmit`.

The root solution is to change the `moduleResolution` in tsconfig.json to ['node16', 'nodenext', 'bundler'], but these values do not correspond to the current setting of `“module”: “commonjs”`.

However, [this comment](https://github.com/rollup/rollup/issues/5199#issuecomment-2374040117) may be helpful.

**Comment by venables** [comment]
Thanks @mdoi2 !

**Comment by venables** [comment]
Released as part of v8.0.1. Thanks again!

**Comment by julienw** [comment]
I have `"exclude": ["node_modules"]` in my tsconfig.json so that must be it :-) thanks again for the quick fix and the release.

**Pull request merged**
